### ISSUE TITLE
The Colab doesn't work

### ISSUE THREAD

**Issue by alarmgoose** [camenduru/LLaVA-colab#6]
It won't load the model so all I get is a error. I would use the demo but half the time its down. Been trying to get it to work without luck and I tried each colab minus the high ram one. :/

**Comment by camenduru** [comment]
it is working 🥳

![image](https://github.com/camenduru/LLaVA-colab/assets/54370274/26ba4ba6-e8f6-4657-903f-b9dde7d462ba)

**Comment by alarmgoose** [comment]
![screens](https://github.com/camenduru/LLaVA-colab/assets/143303011/c6323242-4f17-42f8-a3fc-1e655a5dd429)

I should have been more detail. This is the problem I'm having. I've went to replicate though and have been using the 1.6 34b one there which is very detail. Not sure what is going on with this one or what I'm doing wrong.
